services:
  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - assessment4
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: twoge_kube  
    container_name: backend
    ports:
      - "80:80"
    environment:
      - SQLALCHEMY_DATABASE_URI=${DB_TYPE}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - assessment4

networks:
  assessment4:
    name: assessment4
    driver: bridge

volumes:
  postgres-data: {}