apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: twoge-storage-jose
  namespace: jose
provisioner: ebs.csi.aws.com #On AWS EBS
# provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
# volumeBindingMode: Immediate
volumeBindingMode: WaitForFirstConsumer
