apiVersion: v1
kind: Service
metadata:
  name: twoge-service
  namespace: jose
spec:
  selector:
    app: twoge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # type: NodePort
  type: LoadBalancer